### PR TITLE
Make it compatible with latest rate-limit-redis

### PR DESCRIPTION
**Pull request by AdrianoRuberto**
This should close https://github.com/express-rate-limit/express-slow-down/issues/24

- Modify `incr` function to `increment`
- `increment` can handle promise-based store function

### CODE REVIEW

**Comment by AdrianoRuberto** [comment]
@nfriedly I'm quite sure it's a false negative (should be < 100ms but got 154ms **only** on macos ...)

**Comment by nfriedly** [comment]
Hey, thanks for doing this, and sorry for not getting back to you sooner. Unfortunately I don't think I can merge this in as-is, because it breaks backwards-compatibility with ever current express-slow-down user.  

I think that rebuilding express-slow-down on top of express-rate-limit, as described in https://github.com/express-rate-limit/express-slow-down/issues/24#issuecomment-1255579856 is probably the right way to go, but I'd also be willing to merge in a PR that just added modern store support as long as it didn't break current users. Ideally, the existing tests shouldn't need any changes, and new tests could be added to cover the .increment() api.

I think you're right about the tests, I'm re-running them now. I thought I had ironed out all of the flakiness, but apparently not.

**Comment by AdrianoRuberto** [comment]
@nfriedly should be retro compatible and handle `.increment` function

**Comment by nfriedly** [comment]
Thanks! I like this a lot!

Sorry for being slow to respond, I've dealing with some family stuff. I'm also on my phone right now, so I'm going to wait until I'm on a computer to take a closer look and then merge and release it. Hopefully I can do that tomorrow.

**Comment by nfriedly** [comment]
This is now live on npm as v1.6.0!

Please test it out and let me know if it works for you.

Thanks again!

**Pull request merged**
